use_frameworks!
inhibit_all_warnings!

target 'RxDataSources-Texture_Example' do
  pod 'RxDataSources-Texture', :path => '../'
  pod 'RxOptional'
  pod 'Alamofire'
  pod 'RxAlamofire'

  target 'RxDataSources-Texture_Tests' do
    inherit! :search_paths
    
  end
end
