name: CI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    env:
      WORKSPACE: RxDataSources-Texture.xcworkspace
      SCHEME: RxDataSources-Texture-Package
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Generate Xcode Project
      run: make project
      
    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
